export function up(knex) {
  return knex.schema.createTable('applyforwork', function (table) {
    table.increments('id').unsigned().notNullable().primary();
    table.integer('age', 11);
    table.string('position', 50).collate('utf16_general_ci');
    table.string('placeOfWork', 100).collate('utf16_general_ci');
    table.string('prefix', 10).collate('utf16_general_ci');
    table.string('firstName', 100).collate('utf16_general_ci');
    table.string('lastName', 100).collate('utf16_general_ci');
    table.string('nickName', 50).collate('utf16_general_ci');
    table.string('nation', 50).collate('utf16_general_ci');
    table.string('race', 50).collate('utf16_general_ci');
    table.string('expectedSalary', 20).collate('utf16_general_ci');
    table.string('permanentAddress', 255).collate('utf16_general_ci');
    table.string('realAddress', 255).collate('utf16_general_ci');
    table.string('dealSalary', 20).collate('utf16_general_ci');
    table.string('email', 255).collate('utf16_general_ci');
    table.string('phoneNumber', 20).collate('utf16_general_ci');
    table.string('idCardNumber', 20).collate('utf16_general_ci');
    table.string('idCardRegisterFrom', 200).collate('utf16_general_ci');
    table.string('fatherName', 100).collate('utf16_general_ci');
    table.string('fatherAge', 10).collate('utf16_general_ci');
    table.string('fatherAddressAndPhone', 255).collate('utf16_general_ci');
    table.string('motherName', 100).collate('utf16_general_ci');
    table.string('motherAge', 10).collate('utf16_general_ci');
    table.string('motherAddressAndPhone', 255).collate('utf16_general_ci');
    table.string('wifeName', 255).collate('utf16_general_ci');
    table.string('wifeAge', 10).collate('utf16_general_ci');
    table.string('wifeAddressAndPhone', 255).collate('utf16_general_ci');
    table.string('educationLv1', 100).collate('utf16_general_ci');
    table.string('schoolAndMajor1', 255).collate('utf16_general_ci');
    table.string('educationalQualification1', 255).collate('utf16_general_ci');
    table.string('educationLv2', 100).collate('utf16_general_ci');
    table.string('schoolAndMajor2', 255).collate('utf16_general_ci');
    table.string('educationalQualification2', 255).collate('utf16_general_ci');
    table.string('educationLv3', 100).collate('utf16_general_ci');
    table.string('schoolAndMajor3', 255).collate('utf16_general_ci');
    table.string('educationalQualification3', 255).collate('utf16_general_ci');
    table.string('oldCompanyName1', 100).collate('utf16_general_ci');
    table.string('oldPosition1', 100).collate('utf16_general_ci');
    table.string('oldSalary1', 20).collate('utf16_general_ci');
    table.string('oldWorkDuration1', 50).collate('utf16_general_ci');
    table.string('oldJobDescription1', 255).collate('utf16_general_ci');
    table.string('oldCompanyPhone1', 20).collate('utf16_general_ci');
    table.string('oldCompanyExitreason1', 255).collate('utf16_general_ci');
    table.string('oldCompanyName2', 100).collate('utf16_general_ci');
    table.string('oldPosition2', 100).collate('utf16_general_ci');
    table.string('oldSalary2', 20).collate('utf16_general_ci');
    table.string('oldWorkDuration2', 50).collate('utf16_general_ci');
    table.string('oldJobDescription2', 255).collate('utf16_general_ci');
    table.string('oldCompanyPhone2', 20).collate('utf16_general_ci');
    table.string('oldCompanyExitreason2', 255).collate('utf16_general_ci');
    table.string('oldCompanyName3', 100).collate('utf16_general_ci');
    table.string('oldPosition3', 100).collate('utf16_general_ci');
    table.string('oldSalary3', 20).collate('utf16_general_ci');
    table.string('oldWorkDuration3', 50).collate('utf16_general_ci');
    table.string('oldJobDescription3', 255).collate('utf16_general_ci');
    table.string('oldCompanyPhone3', 20).collate('utf16_general_ci');
    table.string('oldCompanyExitreason3', 255).collate('utf16_general_ci');
    table.string('computerSkills', 255).collate('utf16_general_ci');
    table.string('languageSkills', 255).collate('utf16_general_ci');
    table.string('fileAttach1', 255).collate('utf16_general_ci');
    table.string('fileAttach2', 255).collate('utf16_general_ci');
    table.string('fileAttach3', 255).collate('utf16_general_ci');
    table.string('fileAttach4', 255).collate('utf16_general_ci');
    table.string('fileAttach5', 255).collate('utf16_general_ci');
    table.string('fileAttach6', 255).collate('utf16_general_ci');
    table.string('fileAttach7', 255).collate('utf16_general_ci');
    table.string('fileAttach8', 255).collate('utf16_general_ci');
    table.string('fileAttach9', 255).collate('utf16_general_ci');
    table.string('candidateSign', 255).collate('utf16_general_ci');
    table.string('candidatePicture', 255).collate('utf16_general_ci');
    table.string('interviewerComment', 255).collate('utf16_general_ci');
    table.string('interviewerSign', 255).collate('utf16_general_ci');
    table.string('interviewerName', 255).collate('utf16_general_ci');
    table.string('hrComment', 255).collate('utf16_general_ci');
    table.string('hrSign', 255).collate('utf16_general_ci');
    table.string('hrName', 255).collate('utf16_general_ci');
    table.string('registerDate', 255).collate('utf16_general_ci');
    table.string('birthDate', 255).collate('utf16_general_ci');
    table.string('idExpireDate', 255).collate('utf16_general_ci');
    table.string('status', 50).collate('utf16_general_ci');
  });
}

export function down(knex) {
  return knex.schema.dropTable('applyforwork');
}
